### PR TITLE
Make bundle tests CI independent

### PR DESCRIPTION
**Pull request by beliaev-maksim**
provide options to CI when it is triggered
add TOX targets to run depending on args and env vars

### CODE REVIEW

**Review by DnPlas — COMMENTED** [review]
Thanks @beliaev-maksim, just to understand the reasoning for this change, what do you mean 1.6 tests are not up to date?

**Comment by beliaev-maksim** [comment]
@DnPlas 
I mean when I created bundle tests I just took two templates, for 1.6 and for 1.7

however, I worked only for 1.7 in the post PRs, that means that 1.6 is almost broken. And since we do not expect any changes to the bundle, then I think we need to drop them and continue focusing on 1.7 and 1.8

**Comment by DnPlas** [comment]
> is there a compromise where we take the things you've done to 1.7 and apply them to 1.6 tests? We support 1.6 still, so it would be good to have tests for it. Is there something that would make 1.6 updates really different from 1.7?

Yeah, my next comment would've been related to this. IMO, 1.6 should still be tested until we actually release 1.8, which will happen until ~october. Plus, IMO a better transition to stop supporting this test would be to disable the older versions as we release.

**Comment by ca-scribner** [comment]
Yeah stopping supporting old tests as versions go out of the support window was what we decided on in the past.  Maybe the current big refactors change that a bit, but in general the idea is there should always be versions `current` and `current-1` available in our test suite.

**Review by i-chvets — APPROVED** [review]
Approved.

**Pull request merged**
