### PR TITLE
[KF-5958] Upgrade to Python3.10+

### PR DESCRIPTION
**Pull request by deusebio**
Testing the upgrade of the Kubeflow UAT to Python 3.10 or 3.12, see https://github.com/canonical/charmed-kubeflow-uats/pull/137

The AKS and EKS runs have been positive using noble with python 3.12:

* [EKS](https://github.com/canonical/bundle-kubeflow/actions/runs/11978574125/job/33398942758)
* [AKS](https://github.com/canonical/bundle-kubeflow/actions/runs/11976053369/job/33390856205)

### CODE REVIEW

**Comment by Gu1nness** [comment]
@deusebio I think you mixed DPE-5958 and KF-5958 in the PR title, this is Kubeflow not Data Platform

**Comment by deusebio** [comment]
@Gu1nness ops, fixed it! thanks!

**Comment by deusebio** [comment]
Re-running tests using UATs from https://github.com/canonical/charmed-kubeflow-uats/pull/137, both for

* [EKS](https://github.com/canonical/bundle-kubeflow/actions/runs/12184165663)
* [AKS](https://github.com/canonical/bundle-kubeflow/actions/runs/12184161695)

**Review by misohu — DISMISSED** [review]
Looking good thanks

**Comment by deusebio** [comment]
Re-run the tests:
* [EKS](https://github.com/canonical/bundle-kubeflow/actions/runs/12286332304)
* [AKS](https://github.com/canonical/bundle-kubeflow/actions/runs/12286329916)

All green!

**Review by misohu — APPROVED** [review]

**Pull request merged**
